name: Expense Tracker CI

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build-test:
    name: Build, Test and Docker
    runs-on: ubuntu-latest

    steps:

      # ----------------------------------------
      # 1. Checkout source code
      # ----------------------------------------
      - name: Checkout source code
        uses: actions/checkout@v4


      # ----------------------------------------
      # 2. Setup Java 21
      # ----------------------------------------
      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven


      # ----------------------------------------
      # 3. Build and test backend
      # ----------------------------------------
      - name: Build and test backend
        working-directory: backend
        run: |
          chmod +x mvnw
          ./mvnw -B -ntp clean package -DskipTests=false


      # ----------------------------------------
      # 4. Setup Node.js
      # ----------------------------------------
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm
          cache-dependency-path: frontend/package-lock.json


      # ----------------------------------------
      # 5. Install frontend dependencies
      # ----------------------------------------
      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci


      # ----------------------------------------
      # 6. Build frontend
      # ----------------------------------------
      - name: Build frontend
        working-directory: frontend
        run: npm run build


       # ----------------------------------------
      # 7. Build backend Docker image
      # ----------------------------------------
      - name: Build backend Docker image
        run: |
          docker build \
            -t expense-backend:latest \
            ./backend


      # ----------------------------------------
      # 8. Create Docker network
      # ----------------------------------------
      - name: Create Docker network
        run: |
          docker network create expense-network


      # ----------------------------------------
      # 9. Start PostgreSQL
      # ----------------------------------------
      - name: Start PostgreSQL
        run: |
          docker run -d \
            --name expense-postgres \
            --network expense-network \
            -e POSTGRES_DB=expense_tracker_db \
            -e POSTGRES_USER=postgres \
            -e POSTGRES_PASSWORD=123 \
            postgres:15-alpine


      # ----------------------------------------
      # 10. Start Redis
      # ----------------------------------------
      - name: Start Redis
        run: |
          docker run -d \
            --name expense-redis \
            --network expense-network \
            redis:7-alpine


      # ----------------------------------------
      # 11. Wait for PostgreSQL and Redis
      # ----------------------------------------
      - name: Wait for dependencies
        run: |
          sleep 10

          echo "PostgreSQL:"
          docker ps --filter name=expense-postgres

          echo "Redis:"
          docker ps --filter name=expense-redis


      # ----------------------------------------
      # 12. Run backend container
      # ----------------------------------------
      - name: Run backend container
        run: |
          docker run -d \
            --name expense-backend-test \
            --network expense-network \
            -e DB_HOST=expense-postgres \
            -e REDIS_HOST=expense-redis \
            -p 8080:8080 \
            expense-backend:latest


      # ----------------------------------------
      # 13. Wait for backend
      # ----------------------------------------
      - name: Wait for backend
        run: |
          sleep 20


      # ----------------------------------------
      # 14. Check containers and logs
      # ----------------------------------------
      - name: Check containers
        run: |
          docker ps -a

          echo "========== BACKEND LOGS =========="
          docker logs expense-backend-test

          echo "========== POSTGRES LOGS =========="
          docker logs expense-postgres

          echo "========== REDIS LOGS =========="
          docker logs expense-redis


      # ----------------------------------------
      # 15. Verify backend
      # ----------------------------------------
      - name: Verify backend container
        run: |
          STATUS=$(docker inspect -f '{{.State.Status}}' expense-backend-test)

          echo "Backend container status: $STATUS"

          if [ "$STATUS" != "running" ]; then
            echo "Backend container failed"
            exit 1
          fi


      # ----------------------------------------
      # 16. Cleanup
      # ----------------------------------------
      - name: Cleanup containers
        if: always()
        run: |
          docker stop expense-backend-test || true
          docker stop expense-postgres || true
          docker stop expense-redis || true

          docker rm expense-backend-test || true
          docker rm expense-postgres || true
          docker rm expense-redis || true

          docker network rm expense-network || true
